name = "traintracker-fr"
compatibility_date = "2024-07-04"
pages_build_output_dir = "out"

[env.production]
compatibility_date = "2024-07-04"
routes = [
  { pattern = "traintracker.fr", custom_domain = true },
  { pattern = "*.traintracker.fr", custom_domain = true }
]

[env.production.vars]
ENVIRONMENT = "production"

[env.staging]
compatibility_date = "2024-07-04"
routes = [
  { pattern = "staging.traintracker.fr", custom_domain = true }
]

[env.staging.vars]
ENVIRONMENT = "staging"