name = "traintracker-france"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "your-preview-kv-namespace-id"