name = "traintracker-fr"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".next"

[env.production]
name = "traintracker-fr"
routes = [
  { pattern = "traintracker.fr/*", zone_name = "traintracker.fr" },
  { pattern = "www.traintracker.fr/*", zone_name = "traintracker.fr" }
]

[vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_SITE_URL = "https://traintracker.fr"
NEXT_PUBLIC_SITE_NAME = "Train Tracker France"

# Environment variables (set in Cloudflare dashboard)
# SNCF_API_KEY = "your_sncf_api_key_here"
# NEXT_PUBLIC_GA_MEASUREMENT_ID = "your_ga_measurement_id_here"